CREATE TABLE IF NOT EXISTS `auction_table` (
  `auctionid` INT UNSIGNED NOT NULL DEFAULT 0,
  `ownerid` INT UNSIGNED NOT NULL DEFAULT 0,
  `itemid` INT UNSIGNED NOT NULL DEFAULT 0,
  `count` INT UNSIGNED NOT NULL DEFAULT 0,
  `enchant` INT UNSIGNED NOT NULL DEFAULT 0,
  `costid` INT UNSIGNED NOT NULL DEFAULT 0,
  `costcount` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (auctionid)
);