CREATE TABLE IF NOT EXISTS character_kills_snapshot (
  charId INT UNSIGNED NOT NULL DEFAULT 0,
  pvpkills INT UNSIGNED NOT NULL DEFAULT 0,
  pkkills INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (charId)
);